version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - install_dependencies.sh
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root