version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-11-amazon-corretto.x86_64"
phases:
  install:
    commands:
    - echo installing maven...
    - yum update -y
    - "sudo wget \"http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo\""
    - "sudo sed -i s/\\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo"
    - "sudo yum install -y apache-maven"
  build:
    commands:
    - echo building the project
    - mvn package
artifacts:
  files:
  - target/*.jar
  - start_server.sh
  - appspec.yml
  discard-paths: yes
cache:
  paths:
  - '/root/.m2/**/*'